# Generated by Django 3.0.8 on 2020-08-30 21:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_auto_20200830_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
